name: Docker

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    name: Build
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      packages: write
      security-events: read
      pull-requests: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          provenance: mode=max
          sbom: true
          tags: ghcr.io/${{ github.repository }}:latest
          push: true

      - name: Delete untagged images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
